name: 'OSS Contribution Histogram Generator'
description: 'Generate contribution histograms for GitHub users across repositories'
author: 'peterxcli'

inputs:
  targets:
    description: 'Target repositories and usernames (format: username,owner/repo [username,owner/repo ...])'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  output_dir:
    description: 'Directory to save the generated PNG files'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0 pandas==2.2.2 matplotlib==3.8.4 tqdm==4.67.0

    - name: Run script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
      run: python ${{ github.action_path }}/gh-contribution-graph-generator.py ${{ inputs.targets }} 