name: 'OSS Contribution Histogram Generator'
description: 'Generate contribution histograms for GitHub users across repositories'
author: 'peterxcli, jason810496'

inputs:
  targets:
    description: 'Target repositories and usernames (format: username,owner/repo [username,owner/repo ...])'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  output_dir:
    description: 'Directory to save the generated PNG files'
    required: false
    default: '.'
  exclude_authored_from_reviewed:
    description: 'Whether to exclude PRs authored by the user from the reviewed count'
    required: false
    default: 'false'
  theme:
    description: 'Theme for the histogram (default: "default")'
    required: true
    default: 'default'
  authored_color:
    description: 'Color for authored contributions (default: based on theme)'
    required: false
  reviewed_color:
    description: 'Color for reviewed contributions (default: based on theme)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        OUTPUT_DIR="$PWD/${{ inputs.output_dir }}"
        cd ${{ github.action_path }}
        python gh-contribution-graph-generator.py \
          --targets "${{ inputs.targets }}" \
          --output-dir "$OUTPUT_DIR" \
          ${{ inputs.exclude_authored_from_reviewed == 'true' && '--exclude-authored-from-reviewed' || '' }} \
          --theme "${{ inputs.theme }}" \
          ${{ inputs.authored_color && format('--authored-color {0}', inputs.authored_color) || '' }} \
          ${{ inputs.reviewed_color && format('--reviewed-color {0}', inputs.reviewed_color) || '' }}
